include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

test:1.2:
  extends:
    - .julia:1.2
    - .test
  tags:
    - nvidia
  image: nvidia/cuda:latest

coverage:
  allow_failure: true
  only:
  - master
